### ISSUE TITLE
Auto reloading after 12 hours

### ISSUE THREAD

**Issue by ccev** [ccev/pogodata#2]
save the time when raw data was downloaded. When it's older than 12 (or 24?) hours, re-download it. (Also useful for #1)

The time should be configureable.

**Comment by Tabbomat** [comment]
You could also use the github api (for example https://api.github.com/repos/Furtif/POGOProtos/commits?path=base/base.proto&page=1&per_page=1) to check if a file has been modified since the last download, and re-download and update the pickle only when necessary.

**Comment by ccev** [comment]
That's a great idea, thank you

**Comment by ccev** [comment]
I have decided against checking file commit dates for now. PogoData.reload() does not currently support reloading individual parts and implementing it would require effort that I'm not willing to put in for saving like 5 seconds every 24 hours.
